version: '3'

services:
  frontend:
    build: .
    volumes: 
      - './:/var/www/html/'
    ports:
      - '8083:80'
      - '443:443' #for future ssl

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=sales
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8084:80'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
